// Regenerates src/data/swfdump.ts from the swfdump repo.
// Run after adding SWFs to NV4s/swfdump:  node scripts/gen-catalog.mjs
import { writeFile } from 'node:fs/promises';

const REPO = 'NV4s/swfdump';
const OUT = new URL('../src/data/swfdump.ts', import.meta.url);

const json = async (url) => {
  const res = await fetch(url, { headers: { 'user-agent': 'nexus-catalog' } });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
  return res.json();
};

const { sha } = await json(`https://api.github.com/repos/${REPO}/commits/main`);
const { tree, truncated } = await json(
  `https://api.github.com/repos/${REPO}/git/trees/${sha}?recursive=1`,
);
if (truncated) throw new Error('tree response truncated — needs pagination');

// Chunk files (`<name>.swf.001`, `.002`, …) are skipped by the `.swf` filter —
// they are the fallback for an LFS file, not entries of their own.
//
// A file in LFS reports the ~130-byte pointer as its tree size, which would send
// it to jsDelivr instead of the media endpoint and serve the pointer text as if
// it were a game. Read the real byte count out of the pointer instead.
// ponytail: 1 KB threshold — the smallest real SWF in the dump is ~10 KB, and a
// tiny file that is not a pointer throws below rather than being guessed at.
const LFS_POINTER_MAX = 1024;
const realSize = async ([path, size]) => {
  if (size > LFS_POINTER_MAX) return [path, size];
  const encoded = path.split('/').map(encodeURIComponent).join('/');
  const res = await fetch(`https://raw.githubusercontent.com/${REPO}/${sha}/${encoded}`, {
    headers: { 'user-agent': 'nexus-catalog' },
  });
  const match = (await res.text()).match(/^size (\d+)$/m);
  if (!match) throw new Error(`tiny SWF ${path} (${size} B) is not an LFS pointer`);
  return [path, Number(match[1])];
};

const files = (
  await Promise.all(
    tree
      .filter((n) => n.type === 'blob' && n.path.toLowerCase().endsWith('.swf'))
      .map((n) => [n.path, n.size])
      .map(realSize),
  )
).sort((a, b) => a[0].localeCompare(b[0]));

const body = `// GENERATED by scripts/gen-catalog.mjs — do not edit by hand.
// Source: https://github.com/${REPO} @ ${sha}

export const SWFDUMP_SHA = '${sha}';

/** [repo path, bytes] for every SWF in the dump. */
export const SWFDUMP_FILES: ReadonlyArray<readonly [string, number]> = [
${files.map(([p, s]) => `  [${JSON.stringify(p)}, ${s}],`).join('\n')}
];
`;

await writeFile(OUT, body);
console.log(`wrote ${files.length} entries @ ${sha.slice(0, 7)}`);
