// Regenerates src/data/swfdump.ts from the swfdump repo.
// Run after adding SWFs to NV4s/swfdump:  node scripts/gen-catalog.mjs
import { writeFile } from 'node:fs/promises';

const REPO = 'NV4s/swfdump';
const OUT = new URL('../src/data/swfdump.ts', import.meta.url);

const json = async (url) => {
  const res = await fetch(url, { headers: { 'user-agent': 'nexus-catalog' } });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
  return res.json();
};

const { sha } = await json(`https://api.github.com/repos/${REPO}/commits/main`);
const { tree, truncated } = await json(
  `https://api.github.com/repos/${REPO}/git/trees/${sha}?recursive=1`,
);
if (truncated) throw new Error('tree response truncated — needs pagination');

const files = tree
  .filter((n) => n.type === 'blob' && n.path.toLowerCase().endsWith('.swf'))
  .map((n) => [n.path, n.size])
  .sort((a, b) => a[0].localeCompare(b[0]));

const body = `// GENERATED by scripts/gen-catalog.mjs — do not edit by hand.
// Source: https://github.com/${REPO} @ ${sha}

export const SWFDUMP_SHA = '${sha}';

/** [repo path, bytes] for every SWF in the dump. */
export const SWFDUMP_FILES: ReadonlyArray<readonly [string, number]> = [
${files.map(([p, s]) => `  [${JSON.stringify(p)}, ${s}],`).join('\n')}
];
`;

await writeFile(OUT, body);
console.log(`wrote ${files.length} entries @ ${sha.slice(0, 7)}`);
